# Possible Cabinet Appointees
:toc:

## SUMMARY
While it is not possible to name exact, final appointees, it may be a useful exercise to discuss publicly the sorts of out-of-the-box choices a PG2029 appointment process will require. 

## Vice President
While elected, our process allows the Presidential candidate to effectively install the Vice President of their choice. +

This choice must be whoever seems most likely to help win the General Election. +

"Chemistry" with the Presidential candidate and with the Democratic Party needs to be a secondary concern.  

## Secretary of State:
Top Choice: Former President Barack Obama: 

The primary disadvantages of his selection will include the following:

. Political overshadowing of the new President. 
. MAGA loyalists will be motivated to continue their scorched earth campaigns opposing PG2029.

The primary advantages of his selection will include the following:

. Internationally, he will lend credibility to the narrative we must use with our erstwhile allies that the US is firmly repudiating the MAGA priorities of the DJT era. 
. Both Domestically and Internationally, his immense experience will make in an invaluable assistant to a President who will be heavily engaged in domestic PG2029. 
. He can also be deployed domestically to assist PG2029 in the legitimate role of explaining our post-MAGA construction to the country as an explanation to Americans of how the USA is explaining itself abroad.  
. During confirmation, he can legitimately employ the stratagem of deferring difficult questions from any MAGA Republicans on the Senate Committee on Foreign Relations in two ways: 
.. Either as irrelevant because they might be questioning previous domestic policies, or
.. as requiring closed-door answers because of sensitivity of the material: practically any area of difficult questioning can be handled in this way.



## Secretary of Defense:


## Attorney General:

## Secretary of Commerce

## Head of ROLA (formerly DOGE)

