---
sort_number: 020
---
= The Inescapable Logic of Our Political Parties 
:doctype: book
:table-caption: Data Set
:imagesdir: /content/media/images/
:page-liquid:
:page-stage: 00
:page-draft_complete: 75%
:page-authors: Vector Hasting
:page-todos: Add footnotes.
:showtitle:

== Party Is Destiny

Party should not be Destiny, but for the struggle ahead, it is true. 

In the United States' system of voting, because we have a Presidency, there is a winner-take-all quality to Presidential elections. 

Whenever there is a winner-take-all situation, it adds evolutionary pressure toward gigantism. footnote:[This is easy to find references for, we need a good footnote here.]

We can see this in nature (before human beings upended the way evolution worked). 
Gigantism was a pervasive evolutionary strategy because the consequences of death (winner take all) made largeness a reasonable strategy. Think of the dinosaurs and the Mastodon (only done-in by humans). footnote:[This should also be easy to find a simple reference for.]

This winner-take-all influence has long-ago led to a two-party system in the United States. 

Unless we un-make the Second Article branch of government, or make it into a power-sharing body, we will be stuck with at most two influential parties. 

== Single Party Rule, or else...

If we lose this struggle, we will be left with a single-party rule. 

This is the clear goal of the MAGA regime. footnote:[Just read any scree where they cast Democrats as evil and illegitimate. Perhaps there's a logical breakdown of these somewhere that we can link to here.]
It is the goal of fascism and authoritarianism. 

A single party lends the apparent legitimacy of elections because party leaders can be elected, but it maintains control over the populace with a single choice of party. 

The one-party system is what runs Russia and the Peoples Republic of China. 
This system is rife with more corruption than any other save for absolute dictatorships. footnote:[This may be harder to find a footnote for, it may simply be something that falls into the category of the obvious.]

== No Choice but the Democratic Party

Because our only hope of resisting One-Party Rule is to maintain at least Two-Party Competition, Project Liberty 2029 will speak to the need to elect Democrats. 

This is not because Democrats are necessarily better as a party than Republicans. 
(Though economically, one can marshall convincing statistics that they are a better party because of their focus on equity across society. footnote:[There should be a link here to Simon Rosenberg's Hopium Chronicles article exploring this data.]

This is because there is no practical path back to Liberty and Justice for All in America without the Democratic party winnning back power. 

Nonetheless, Project Liberty 2029 must pressure the Democrats to adopt as many of our proposals as possible in order to safeguard Freedom for the future. 
